name: my_flutter_app
description: "A new Flutter project."

# Logo launcher
flutter_icons:
  android: true
  ios: true
  image_path: 'assets\images\ic_launcher.png'

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  hexcolor: ^3.0.1
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  another_flushbar: ^1.12.30
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/user.png
    - assets/images/icons/notification-bell.png
    - assets/images/icons/search.png
    - assets/images/icons/specialty_bag.png
    - assets/images/icons/message.png
    - assets/images/icons/medical-star.png
    - assets/images/icons/hospital_heading.png
    - assets/images/icons/clinic.png

    # Banner image
    - assets/images/banner/banner1.png
    - assets/images/banner/banner2.png
    - assets/images/banner/banner3.png
    - assets/images/banner/banner4.png
    - assets/images/banner/banner5.png

    # Doctor image
    - assets/images/doctor/doctor1.png
    - assets/images/doctor/doctor2.png
    - assets/images/doctor/doctor3.png
    - assets/images/doctor/doctor4.png
    - assets/images/doctor/doctor5.png
    - assets/images/doctor/doctor6.png
    - assets/images/doctor/doctor7.png
    - assets/images/doctor/doctor8.png
    - assets/images/doctor/doctor9.png
    - assets/images/doctor/doctor10.png

    # Hospital image
    - assets/images/hospital/an-binh.png
    - assets/images/hospital/binh-tan.png
    - assets/images/hospital/le-van-thinh.png
    - assets/images/hospital/nha-be.png
    - assets/images/hospital/quan-4.png
    - assets/images/hospital/quan-y-175.png
    - assets/images/hospital/rang-ham-mat.png
    - assets/images/hospital/tai-mui-hong.png
    - assets/images/hospital/ung-buou.png
    - assets/images/hospital/y-hoc-co-truyen.png

    # Clinic image
    - assets/images/clinic/alma.png
    - assets/images/clinic/hello-doctor.png
    - assets/images/clinic/long-chau.png
    - assets/images/clinic/my-my.png
    - assets/images/clinic/nhi-dong-315.png
    - assets/images/clinic/phu-san-315.png
    - assets/images/clinic/san-phu-khoa-13.png
    - assets/images/clinic/shine.png
    - assets/images/clinic/sim-medical.png
    - assets/images/clinic/vnvc.png

    #Feature icon
    - assets/images/icons/feature/doctor.png
    - assets/images/icons/feature/stethoscope.png
    - assets/images/icons/feature/hospital.png
    - assets/images/icons/feature/chat.png
    - assets/images/icons/feature/phone.png
    - assets/images/icons/feature/bag.png
    - assets/images/icons/feature/protection.png
    - assets/images/icons/feature/vaccine.png
    - assets/images/icons/feature/group.png

    # Bottom navigation icon
    - assets/images/icons/bottom-navigation/home.png
    - assets/images/icons/bottom-navigation/home_active.png
    - assets/images/icons/bottom-navigation/calendar.png
    - assets/images/icons/bottom-navigation/calendar_active.png
    - assets/images/icons/bottom-navigation/chat-bubble.png
    - assets/images/icons/bottom-navigation/chat-bubble_active.png
    - assets/images/icons/bottom-navigation/user_account.png
    - assets/images/icons/bottom-navigation/user_account_active.png

    # Specialty icon
    - assets/images/icons/specialty/chan-doan-hinh-anh.png
    - assets/images/icons/specialty/chan-thuong-chinh-hinh.png
    - assets/images/icons/specialty/co-xuong-khop.png
    - assets/images/icons/specialty/da-khoa.png
    - assets/images/icons/specialty/da-lieu.png
    - assets/images/icons/specialty/dinh-duong.png
    - assets/images/icons/specialty/gay-me-hoi-suc.png
    - assets/images/icons/specialty/ho-hap.png
    - assets/images/icons/specialty/hoi-suc-cap-cuu.png
    - assets/images/icons/specialty/huyet-hoc.png
    - assets/images/icons/specialty/lao-benh-phoi.png
    - assets/images/icons/specialty/lao-khoa.png
    - assets/images/icons/specialty/nam-khoa.png
    - assets/images/icons/specialty/ngoai-long-nguc-mach-mau.png
    - assets/images/icons/specialty/ngoai-nieu.png
    - assets/images/icons/specialty/ngoai-than-kinh.png
    - assets/images/icons/specialty/ngoai-tiet-nieu.png
    - assets/images/icons/specialty/ngoai-tong-quat.png
    - assets/images/icons/specialty/ngon-ngu-tri-lieu.png
    - assets/images/icons/specialty/nhan-khoa.png
    - assets/images/icons/specialty/nhi-khoa.png
    - assets/images/icons/specialty/noi-than-kinh.png
    - assets/images/icons/specialty/noi-than.png
    - assets/images/icons/specialty/noi-tiet.png
    - assets/images/icons/specialty/noi-tong-quat.png
    - assets/images/icons/specialty/phuc-hoi-chuc-nang-vat-ly-tri-lieu.png
    - assets/images/icons/specialty/rang-ham-mat.png
    - assets/images/icons/specialty/san-phu-khoa.png
    - assets/images/icons/specialty/tai-mui-hong.png
    - assets/images/icons/specialty/tam-ly.png
    - assets/images/icons/specialty/tam-than.png
    - assets/images/icons/specialty/tham-my.png
    - assets/images/icons/specialty/tieu-hoa.png
    - assets/images/icons/specialty/tim-mach.png
    - assets/images/icons/specialty/truyen-nhiem.png
    - assets/images/icons/specialty/ung-buou.png
    - assets/images/icons/specialty/vo-sinh-hiem-muon.png
    - assets/images/icons/specialty/xet-nghiem.png
    - assets/images/icons/specialty/y-hoc-co-truyen.png
    - assets/images/icons/specialty/y-hoc-du-phong.png
    - assets/images/icons/specialty/y-hoc-the-thao.png

    # account icons
    - assets/images/icons/account/add-contact.png
    - assets/images/icons/account/copy.png
    - assets/images/icons/account/exclamation-mark.png
    - assets/images/icons/account/heart.png
    - assets/images/icons/account/hosoYTe.png
    - assets/images/icons/account/logout.png
    - assets/images/icons/account/man.png
    - assets/images/icons/account/settings.png
    - assets/images/icons/account/share.png
    - assets/images/icons/account/support.png
    - assets/images/icons/account/userInfo.png
    - assets/images/icons/account/user.png
    - assets/images/icons/account/woman.png
    - assets/images/icons/account/hoSoUser.png
    - assets/images/icons/account/scan.png
    - assets/images/icons/account/write.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
